services:
  flask:
    build: 
      context: flask-app  #folder where app is
      dockerfile: Dockerfile #dockerfile name
    image: reactiv3dev/flask:latest
    ports:
      - 7070:8080
    env_file:
      - ./flask-app/.env
    environment:
      - APP_VERSION=0.1.0
      - APP_TOKEN=${APP_TOKEN} # docker will warn us if this is not set!
    volumes:
      - flask-data:/data
      #- ./flask-app/my_data:/data
    networks:
      - privatep
    restart: always

  postgres:
    image: postgres:16.3
    ports: 
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: flask_api_db
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private
    restart: always

volumes:
  flask-data:
  postgres-data:

networks:
  private: 
    driver: bridge
    ipam: 
      config:
       - subnet: "10.0.0.0/19"
         gateway: "10.0.0.1"